package com.obabichev.kodama.compiler.metadata

import kotlinx.serialization.json.Json
import java.io.File

/**
 * Loads KSP metadata from the JSON file generated by kodama-ksp-processor.
 *
 * The metadata file is generated at:
 * build/generated/ksp/main/resources/kodama-ksp-metadata.json
 */
class KspMetadataLoader {

    private val json = Json {
        ignoreUnknownKeys = true
        prettyPrint = true
    }

    /**
     * Load table metadata from KSP-generated JSON file.
     *
     * @param metadataFile The kodama-ksp-metadata.json file
     * @return List of table metadata discovered by KSP
     * @throws IllegalArgumentException if file doesn't exist or is invalid
     */
    fun loadMetadata(metadataFile: File): List<KspTableMetadata> {
        require(metadataFile.exists()) {
            "KSP metadata file not found: ${metadataFile.absolutePath}\n" +
            "Make sure KSP has run successfully (check kspKotlin task)"
        }

        val jsonContent = metadataFile.readText()
        val root = json.decodeFromString<KspMetadataRoot>(jsonContent)

        return root.tables
    }

    /**
     * Find KSP metadata file in standard locations.
     *
     * Looks for: build/generated/ksp/main/resources/kodama-ksp-metadata.json
     *
     * @param buildDir The project's build directory
     * @return The metadata file if found
     * @throws IllegalStateException if file not found in standard location
     */
    fun findMetadataFile(buildDir: File): File {
        val standardLocation = buildDir.resolve("generated/ksp/main/resources/kodama-ksp-metadata.json")

        if (standardLocation.exists()) {
            return standardLocation
        }

        throw IllegalStateException(
            "KSP metadata file not found at: ${standardLocation.absolutePath}\n" +
            "Make sure:\n" +
            "1. KSP plugin is applied\n" +
            "2. kodama-ksp-processor is added as ksp() dependency\n" +
            "3. kspKotlin task has run successfully"
        )
    }
}
