package com.obabichev.kodama.compiler.metadata

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

/**
 * Table metadata from KSP JSON file.
 * Contains basic information discovered at compile-time.
 */
@Serializable
data class KspTableMetadata(
    val name: String,
    @SerialName("package")
    val packageName: String,
    val qualifiedName: String
)

/**
 * Complete column metadata extracted from runtime.
 * Contains all information needed for code generation.
 */
data class ColumnMetadata(
    val propertyName: String,      // Kotlin property name (e.g., userName)
    val sqlColumnName: String,     // SQL column name (e.g., user_name)
    val kotlinType: String,        // Kotlin type (e.g., String, Int)
    val isNullable: Boolean,       // True if column can be null
    val isAutoGenerated: Boolean   // True if column is auto-generated (serial, identity)
)

/**
 * Complete table metadata combining KSP and runtime information.
 */
data class TableMetadata(
    val name: String,
    val packageName: String,
    val qualifiedName: String,
    val columns: List<ColumnMetadata>
)

/**
 * Marker interface metadata from KSP JSON file.
 * Represents empty interfaces used for type-safe query result access.
 */
@Serializable
data class KspMarkerMetadata(
    val name: String,
    @SerialName("package")
    val packageName: String,
    val qualifiedName: String,
    val hasMarkerAnnotation: Boolean = false
)

/**
 * Root structure for KSP metadata JSON.
 */
@Serializable
data class KspMetadataRoot(
    val tables: List<KspTableMetadata>,
    val markers: List<KspMarkerMetadata> = emptyList()  // Default to empty for backward compatibility
)
