package com.obabichev.kodama.compiler.data

/**
 * Structured metadata for a single column in a table.
 *
 * This replaces the raw map-based approach with type-safe, self-documenting data.
 *
 * Example:
 * ```
 * ColumnInfo(
 *     propertyName = "userName",
 *     sqlColumnName = "user_name",
 *     kotlinType = "String",
 *     isNullable = false,
 *     isAutoGenerated = false,
 *     isPrimaryKey = true
 * )
 * ```
 */
data class ColumnInfo(
    /**
     * Kotlin property name in camelCase (e.g., "userName", "createdAt")
     */
    val propertyName: String,

    /**
     * SQL column name in snake_case (e.g., "user_name", "created_at")
     */
    val sqlColumnName: String,

    /**
     * Kotlin type as a string (e.g., "String", "Int", "LocalDateTime")
     */
    val kotlinType: String,

    /**
     * Whether this column can be null in the database
     */
    val isNullable: Boolean,

    /**
     * Whether this column is auto-generated (e.g., serial, identity, or has a default value)
     */
    val isAutoGenerated: Boolean,

    /**
     * Whether this column is part of the primary key
     */
    val isPrimaryKey: Boolean = false
) {
    /**
     * Property name in PascalCase for marker interfaces (e.g., "UserName", "CreatedAt")
     */
    val capitalizedName: String
        get() = propertyName.replaceFirstChar { it.uppercase() }

    /**
     * Kotlin type with nullability marker if needed (e.g., "String?", "Int")
     */
    val kotlinTypeWithNullability: String
        get() = if (isNullable) "$kotlinType?" else kotlinType
}
