package com.obabichev.kodama.compiler.data

/**
 * Structured metadata for a complete table.
 *
 * This replaces the raw map-based approach (tableToProperties, tableToPropertyTypes, etc.)
 * with a single, type-safe data structure.
 *
 * Example:
 * ```
 * TableInfo(
 *     name = "Person",
 *     sqlTableName = "person",
 *     columns = listOf(
 *         ColumnInfo("name", "name", "String", false, false, true),
 *         ColumnInfo("age", "age", "Int", false, false, false)
 *     ),
 *     isSubquery = false
 * )
 * ```
 */
data class TableInfo(
    /**
     * Table name in PascalCase (e.g., "Person", "OrderItem")
     * This is the Kotlin object name.
     */
    val name: String,

    /**
     * Package name where the table is defined (e.g., "com.example.schema")
     */
    val packageName: String,

    /**
     * SQL table name in snake_case (e.g., "person", "order_item")
     */
    val sqlTableName: String,

    /**
     * List of columns in this table, in declaration order
     */
    val columns: List<ColumnInfo>,

    /**
     * Whether this is a subquery (aliased subquery result) rather than a real table
     */
    val isSubquery: Boolean = false
) {
    /**
     * Table name in PascalCase (same as name, for consistency)
     */
    val capitalizedName: String
        get() = name.replaceFirstChar { it.uppercase() }

    /**
     * Table name in camelCase for accessor properties (e.g., "person", "orderItem")
     */
    val camelCaseName: String
        get() = name.replaceFirstChar { it.lowercase() }

    /**
     * Get column by property name
     */
    fun columnByProperty(propertyName: String): ColumnInfo? {
        return columns.firstOrNull { it.propertyName == propertyName }
    }

    /**
     * Get all column property names
     */
    val columnPropertyNames: List<String>
        get() = columns.map { it.propertyName }

    /**
     * Get primary key columns
     */
    val primaryKeyColumns: List<ColumnInfo>
        get() = columns.filter { it.isPrimaryKey }

    /**
     * Get non-auto-generated columns (for INSERT statements)
     */
    val nonAutoGeneratedColumns: List<ColumnInfo>
        get() = columns.filter { !it.isAutoGenerated }
}
