package com.obabichev.kodama.compiler.generator

/**
 * Base interface for all code generators.
 * Each generator transforms a domain model into Kotlin source code.
 *
 * This design allows:
 * - Easy testing: generators can be tested with mock models
 * - Composability: generators can be combined
 * - Extensibility: new generators can be added without modifying existing ones
 *
 * @param TModel The type of model this generator accepts
 */
interface CodeGenerator<TModel> {
    /**
     * Generate Kotlin source code from the given model.
     *
     * @param model The domain model to generate code from
     * @return Generated Kotlin source code as a string
     */
    fun generate(model: TModel): String
}

/**
 * Generates a complete Kotlin file with package, imports, and generated code.
 */
interface FileGenerator<TModel> : CodeGenerator<TModel> {
    /**
     * Generate the package declaration.
     */
    fun generatePackage(packageName: String): String = "package $packageName\n\n"

    /**
     * Generate import statements.
     */
    fun generateImports(imports: List<String>): String {
        return if (imports.isEmpty()) {
            ""
        } else {
            imports.joinToString("\n") { "import $it" } + "\n\n"
        }
    }

    /**
     * Generate file header with suppression annotations.
     */
    fun generateFileHeader(): String {
        return """
            |@file:Suppress("UNCHECKED_CAST", "UNUSED_PARAMETER", "MemberVisibilityCanBePrivate")
            |
            |// AUTO-GENERATED by Kodama Compiler Plugin
            |// DO NOT EDIT MANUALLY
            |
            """.trimMargin()
    }
}

/**
 * Composite generator that combines multiple generators.
 * Follows the Composite pattern.
 */
class CompositeGenerator<TModel>(
    private val generators: List<CodeGenerator<TModel>>
) : CodeGenerator<TModel> {
    override fun generate(model: TModel): String {
        return generators.joinToString("\n\n") { it.generate(model) }
    }
}

/**
 * Generator that wraps another generator with a section header comment.
 */
class SectionGenerator<TModel>(
    private val sectionName: String,
    private val delegate: CodeGenerator<TModel>
) : CodeGenerator<TModel> {
    override fun generate(model: TModel): String {
        return buildString {
            appendLine("// " + "=".repeat(76))
            appendLine("// $sectionName")
            appendLine("// " + "=".repeat(76))
            appendLine()
            append(delegate.generate(model))
        }
    }
}
