package com.obabichev.kodama.compiler.generator

/**
 * Orchestrator that combines multiple CodeGenerators into a single output file.
 *
 * Responsibilities:
 * - Collect imports from all generators
 * - Deduplicate and sort imports
 * - Add package declaration and file header
 * - Combine generated code from all generators
 * - Ensure proper spacing between constructs
 *
 * Example usage:
 * ```
 * val generators = listOf(
 *     ColumnMarkerGenerator(ColumnInfo("name", ...)),
 *     TableAccessorGenerator(TableInfo("Person", ...)),
 *     JoinMethodGenerator(...)
 * )
 *
 * val fileGen = FileGenerator(
 *     packageName = "com.example.generated",
 *     fileName = "QueryExtensions.kt",
 *     generators = generators
 * )
 *
 * val output = fileGen.generate()
 * File("output/QueryExtensions.kt").writeText(output)
 * ```
 */
class FileGenerator(
    /**
     * Package name for the generated file (e.g., "com.example.generated")
     */
    val packageName: String,

    /**
     * File name (e.g., "QueryExtensions.kt")
     * Currently informational only; actual file writing happens externally
     */
    val fileName: String,

    /**
     * List of generators to execute, in order.
     * Each generator produces one construct (interface, class, or function).
     */
    val generators: List<CodeGenerator>,

    /**
     * Schema package name for imports (e.g., "com.example.schema")
     */
    val schemaPackage: String,

    /**
     * Additional marker packages to import (for custom marker interfaces)
     */
    val markerPackages: Set<String> = emptySet()
) {
    /**
     * Generate the complete file content.
     *
     * Output structure:
     * ```
     * @file:Suppress("UNCHECKED_CAST")
     *
     * package com.example.generated
     *
     * import com.obabichev.kodama.components.TypedColumn
     * import com.obabichev.kodama.query.QueryState
     *
     * // AUTO-GENERATED by Kodama Compiler Plugin
     * // DO NOT EDIT MANUALLY
     *
     * interface Name
     *
     * class PersonAccessor(...) {
     *     ...
     * }
     *
     * fun from(table: Person): AfterFromQueryBuilder_Person {
     *     ...
     * }
     * ```
     *
     * @return Complete file content as a string
     */
    fun generate(): String {
        // Step 1: Generate code from all generators
        val allCode = generators.joinToString("\n\n") { it.generate() }

        // Step 2: Combine everything
        return buildString {
            // File annotation
            appendLine("@file:Suppress(\"UNCHECKED_CAST\")")
            appendLine()

            // Package declaration
            appendLine("package $packageName")
            appendLine()

            // Imports (using wildcard imports like baseline)
            appendLine("import kotlin.reflect.KClass")
            appendLine("import com.obabichev.kodama.components.*")
            appendLine("import com.obabichev.kodama.components.expression.*")
            appendLine("import com.obabichev.kodama.query.*")
            appendLine("import $schemaPackage.*")
            appendLine("import com.obabichev.kodama.schema.Table")
            appendLine("import java.sql.ResultSet")
            appendLine("import com.obabichev.kodama.execute.*")

            // Add imports for packages containing marker interfaces
            markerPackages.forEach { pkg ->
                if (pkg != packageName) {  // Don't import our own package
                    appendLine("import $pkg.*")
                }
            }

            appendLine()

            // Header comment
            appendLine("// AUTO-GENERATED by Kodama Compiler Plugin")
            appendLine("// DO NOT EDIT MANUALLY")
            appendLine()

            // Generated code
            append(allCode)
        }
    }

    /**
     * Get statistics about this file generation.
     * Useful for logging and debugging.
     */
    fun stats(): FileGenerationStats {
        // Fixed set of imports: JoinType, query.*, schema.*, Table, plus marker packages
        val importCount = 4 + markerPackages.size
        val generatorCount = generators.size

        return FileGenerationStats(
            fileName = fileName,
            packageName = packageName,
            generatorCount = generatorCount,
            importCount = importCount
        )
    }
}

/**
 * Statistics about a file generation operation.
 */
data class FileGenerationStats(
    val fileName: String,
    val packageName: String,
    val generatorCount: Int,
    val importCount: Int
) {
    override fun toString(): String {
        return "Generated $fileName: $generatorCount constructs, $importCount imports"
    }
}
