package com.obabichev.kodama.compiler.generator

import com.obabichev.kodama.compiler.model.CodeGenerationModel

/**
 * Main file generator that orchestrates all individual generators
 * to produce a complete QueryExtensions.kt file.
 *
 * This follows the Facade pattern, providing a simple interface
 * to a complex subsystem of generators.
 */
class KodamaFileGenerator : FileGenerator<CodeGenerationModel> {

    override fun generate(model: CodeGenerationModel): String = buildString {
        // File header
        append(generateFileHeader())

        // Package declaration
        append(generatePackage(model.generatedPackage))

        // Imports
        append(generateImports(getRequiredImports(model)))

        // Type aliases and markers
        append(generateSection("Type Aliases and Markers") {
            generateTypeAliasesAndMarkers(model)
        })

        // Table accessors
        append(generateSection("Table Accessors") {
            generateTableAccessors(model)
        })

        // Result accessor classes
        append(generateSection("Result Accessor Classes") {
            generateResultAccessors(model)
        })

        // Context classes
        append(generateSection("Context Classes") {
            generateContexts(model)
        })

        // INSERT methods
        append(generateSection("INSERT Methods") {
            generateInsertMethods(model)
        })

        // Execute method overloads
        append(generateSection("Execute Method Overloads") {
            generateExecuteMethods(model)
        })
    }

    private fun getRequiredImports(model: CodeGenerationModel): List<String> {
        return listOf(
            "com.obabichev.kodama.components.JoinType",
            "com.obabichev.kodama.query.*",
            "${model.schemaPackage}.*",
            "com.obabichev.kodama.schema.Table"
        )
    }

    private fun generateSection(sectionName: String, block: () -> String): String {
        return buildString {
            appendLine()
            appendLine("// " + "=".repeat(76))
            appendLine("// $sectionName")
            appendLine("// " + "=".repeat(76))
            appendLine()
            append(block())
        }
    }

    private fun generateTypeAliasesAndMarkers(model: CodeGenerationModel): String = buildString {
        val typeAliasGen = TypeAliasGenerator()
        append(typeAliasGen.generate(Unit))
        appendLine()

        // Generate column markers
        val allColumnNames = model.tables.flatMap { table ->
            table.columns.map { it.pascalCaseName }
        }.toSet()
        val columnMarkerGen = ColumnMarkerGenerator()
        append(columnMarkerGen.generate(allColumnNames))
        appendLine()

        // Generate table markers
        val tableMarkerGen = TableMarkerGenerator()
        append(tableMarkerGen.generate(model.tables.map { it.name }))
        appendLine()

        // Generate AllMarker interface
        val allMarkerGen = AllMarkerGenerator()
        append(allMarkerGen.generate(Unit))
    }

    private fun generateTableAccessors(model: CodeGenerationModel): String = buildString {
        val accessorGen = TableAccessorGenerator(model.schemaPackage)
        val orderByAccessorGen = TableOrderByAccessorGenerator(model.schemaPackage)

        model.tables.forEach { table ->
            append(accessorGen.generate(table))
            appendLine()
            append(orderByAccessorGen.generate(table))
            appendLine()
        }
    }

    private fun generateResultAccessors(model: CodeGenerationModel): String = buildString {
        val tableAccessorsGen = TableResultAccessorsGenerator(model.schemaPackage)

        model.tables.forEach { table ->
            append(tableAccessorsGen.generate(table))
        }

        // Generate accessors for multi-column patterns discovered in tests
        val multiColumnAccessorGen = ResultAccessorGenerator()
        model.resultAccessors.forEach { accessor ->
            // Skip if already generated by TableResultAccessorsGenerator
            val isStandardAccessor = accessor.properties.size <= 2
            if (!isStandardAccessor) {
                append(multiColumnAccessorGen.generate(accessor))
                appendLine()
            }
        }
    }

    private fun generateContexts(model: CodeGenerationModel): String = buildString {
        val contextGen = ContextGenerator(model.schemaPackage)

        model.contexts.forEach { context ->
            append(contextGen.generate(context))
            appendLine()
        }
    }

    private fun generateInsertMethods(model: CodeGenerationModel): String = buildString {
        val insertGen = InsertMethodGenerator(model.schemaPackage)

        appendLine("// Type-safe insert methods with all columns as required parameters")
        appendLine()

        model.insertMethods.forEach { insertMethod ->
            append(insertGen.generate(insertMethod))
            appendLine()
        }
    }

    private fun generateExecuteMethods(model: CodeGenerationModel): String = buildString {
        // TODO: Implement ExecuteMethodGenerator
        // This will be added in the next iteration
        appendLine("// Execute method overloads for selection-specific result classes")
        appendLine("// (Implementation pending)")
    }
}
