package com.obabichev.kodama.ksp.model

import com.google.devtools.ksp.symbol.KSFile

/**
 * Model representing an entity interface discovered by KSP.
 *
 * Contains all information needed to generate:
 * - Implementation data class
 * - Factory function
 * - Copy function
 * - Entity binding
 */
data class EntityInterfaceModel(
    val simpleName: String,
    val qualifiedName: String,
    val packageName: String,
    val properties: List<EntityPropertyModel>,
    val propertyImports: List<String>,
    val tableObjectName: String,  // e.g., "Portfolios"
    val tableQualifiedName: String,  // e.g., "com.example.schema.Portfolios"
    val relationshipMethods: List<RelationshipMethodModel> = emptyList(),
    val containingFile: KSFile
) {
    /**
     * The primary key property (marked with @Id or property named "id").
     */
    val idProperty: EntityPropertyModel?
        get() = properties.firstOrNull { it.isPrimaryKey } ?: properties.firstOrNull { it.name == "id" }
}

/**
 * Model representing a property in an entity interface.
 */
data class EntityPropertyModel(
    val name: String,
    val typeName: String,  // Kotlin type name (e.g., "Int", "String?", "BigDecimal")
    val tablePropertyName: String,  // Property name in Table object (e.g., "userId")
    val columnName: String,  // SQL column name for ResultSet (e.g., "user_id")
    val isPrimaryKey: Boolean = false,
    val isAutoGenerated: Boolean = false,  // For SERIAL, BIGSERIAL, etc.
    val isNullable: Boolean = false
)

/**
 * Model representing a relationship method in an entity interface.
 * For example: fun orders(session: EntitySession): List<UserOrder>
 */
data class RelationshipMethodModel(
    val name: String,               // e.g., "orders"
    val returnType: String,         // e.g., "List<UserOrder>" or "User"
    val returnTypeImports: List<String> = emptyList(),  // Imports needed for return type
    val relationshipData: RelationshipData? = null  // Metadata for generating implementation
)

/**
 * Relationship metadata extracted from EntityTable.
 * Used to generate proper relationship method implementations.
 */
sealed interface RelationshipData {
    val targetTableName: String
    val targetTableQualifiedName: String
}

data class OneToManyData(
    override val targetTableName: String,
    override val targetTableQualifiedName: String,
    val foreignKeyColumn: String,
    val primaryKeyColumn: String
) : RelationshipData

data class ManyToOneData(
    override val targetTableName: String,
    override val targetTableQualifiedName: String,
    val foreignKeyColumn: String,
    val primaryKeyColumn: String
) : RelationshipData

data class ManyToManyData(
    override val targetTableName: String,
    override val targetTableQualifiedName: String,
    val junctionTableName: String,
    val junctionTableQualifiedName: String,
    val sourceForeignKeyColumn: String,
    val targetForeignKeyColumn: String,
    val sourcePrimaryKeyColumn: String,
    val targetPrimaryKeyColumn: String
) : RelationshipData
