package com.obabichev.kodama.ksp.model

/**
 * Represents table metadata discovered by KSP.
 * Contains basic information that KSP can extract.
 */
data class KspTableModel(
    val name: String,              // "Person"
    val packageName: String,       // "com.obabichev.kodama.tests.schema"
    val qualifiedName: String,     // "com.obabichev.kodama.tests.schema.Person"
    val columns: List<ColumnModel> = emptyList()  // Column definitions
) {
    fun toJson(): String = """
        {
            "name": "$name",
            "package": "$packageName",
            "qualifiedName": "$qualifiedName"
        }
    """.trimIndent()
}

/**
 * Represents a column in a table.
 */
data class ColumnModel(
    val propertyName: String,       // Kotlin property name (e.g., "userName")
    val columnName: String,         // SQL column name (e.g., "user_name")
    val typeName: String,           // Fully qualified type (e.g., "kotlin.String")
    val isPrimaryKey: Boolean = false,
    val isNullable: Boolean = false,
    val isAutoGenerated: Boolean = false  // For SERIAL, BIGSERIAL, etc.
)
