package com.obabichev.kodama.ksp.model

import kotlinx.serialization.Serializable

/**
 * Runtime metadata extracted from compiled Table objects.
 * This contains the ACTUAL SQL column names from the table definitions.
 */
@Serializable
data class RuntimeMetadataRoot(
    val tables: List<RuntimeTableMetadata>
)

@Serializable
data class RuntimeTableMetadata(
    val name: String,
    val packageName: String,
    val qualifiedName: String,
    val columns: List<RuntimeColumnMetadata>
)

@Serializable
data class RuntimeColumnMetadata(
    val propertyName: String,
    val sqlColumnName: String,  // This is the ACTUAL SQL column name from the table (e.g., "user_id")
    val kotlinType: String,
    val isNullable: Boolean,
    val isAutoGenerated: Boolean
)
