package com.obabichev.kodama.ksp

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.obabichev.kodama.ksp.model.RelationshipModel
import com.obabichev.kodama.ksp.model.TableWithRelationships
import java.io.OutputStreamWriter

/**
 * Generates CanJoin instances from discovered relationships.
 *
 * For each relationship between tables A and B, generates:
 * ```kotlin
 * object ACanJoinB : CanJoin<A, B>
 * ```
 *
 * This allows compile-time join validation.
 */
class CanJoinGenerator(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger
) {

    /**
     * Generate CanJoin instances for all discovered relationships.
     *
     * Output: A single Kotlin file with all CanJoin objects
     * Location: build/generated/ksp/main/kotlin/{package}/CanJoinInstances.kt
     */
    fun generateCanJoinInstances(
        tablesWithRelationships: List<TableWithRelationships>,
        targetPackage: String
    ) {
        if (tablesWithRelationships.isEmpty()) {
            logger.info("Kodama KSP: No relationships found, skipping CanJoin generation")
            return
        }

        // Collect all relationships
        val allRelationships = tablesWithRelationships.flatMap { it.relationships }

        if (allRelationships.isEmpty()) {
            logger.info("Kodama KSP: No relationships found, skipping CanJoin generation")
            return
        }

        logger.info("Kodama KSP: Generating CanJoin instances for ${allRelationships.size} relationship(s)")

        // Generate the Kotlin file
        try {
            val file = codeGenerator.createNewFile(
                dependencies = Dependencies(true),  // Aggregate all sources
                packageName = targetPackage,
                fileName = "CanJoinInstances"
            )

            OutputStreamWriter(file).use { writer ->
                writer.write(generateFileContent(allRelationships, targetPackage))
            }

            logger.info("Kodama KSP: Generated CanJoinInstances.kt in package $targetPackage")
        } catch (e: Exception) {
            // FileAlreadyExistsException means file was created in a previous round, which is fine
            if (e.javaClass.simpleName == "FileAlreadyExistsException") {
                logger.warn("Kodama KSP: CanJoinInstances.kt already exists, skipping generation")
            } else {
                logger.error("Kodama KSP: Failed to generate CanJoin instances: ${e.message}")
                throw e
            }
        }

        // Generate metadata JSON file for Gradle generator to read
        generateMetadataJson(allRelationships, targetPackage)
    }

    /**
     * Generate the content of the CanJoin instances file.
     */
    private fun generateFileContent(
        relationships: List<RelationshipModel>,
        packageName: String
    ): String = buildString {
        // File header
        appendLine("@file:Suppress(\"unused\", \"ClassName\")")
        appendLine()
        appendLine("package $packageName")
        appendLine()

        // Imports
        appendLine("import com.obabichev.kodama.query.CanJoin")

        // Collect unique table names for imports
        val tableNames = relationships.flatMap {
            listOf(it.sourceTable, it.targetTable)
        }.toSet()

        // We'll assume tables are in the same package (common case)
        // In production, would need to track table packages
        tableNames.forEach { tableName ->
            appendLine("import $packageName.$tableName")
        }

        appendLine()
        appendLine("/**")
        appendLine(" * Auto-generated CanJoin instances for compile-time join validation.")
        appendLine(" * Generated by Kodama KSP processor.")
        appendLine(" *")
        appendLine(" * DO NOT EDIT - This file is automatically generated.")
        appendLine(" */")
        appendLine()

        // Generate CanJoin objects
        relationships.forEach { relationship ->
            val objectName = generateCanJoinObjectName(
                relationship.sourceTable,
                relationship.targetTable
            )

            appendLine("/**")
            appendLine(" * Allows joining from ${relationship.sourceTable} to ${relationship.targetTable}.")
            appendLine(" * Based on ${relationship.relationshipType} relationship.")
            appendLine(" */")
            appendLine("object $objectName : CanJoin<${relationship.sourceTable}, ${relationship.targetTable}>")
            appendLine()
        }
    }

    /**
     * Generate a name for the CanJoin object.
     *
     * Convention: SourceCanJoinTarget
     * Example: PersonCanJoinOrder
     */
    private fun generateCanJoinObjectName(sourceTable: String, targetTable: String): String {
        return "${sourceTable}CanJoin${targetTable}"
    }

    /**
     * Generate JSON metadata file containing all table pairs that have CanJoin instances.
     *
     * This metadata is used by the Gradle code generator to conditionally add
     * CanJoin constraints only to table pairs that have declared relationships.
     *
     * Output location: build/generated/ksp/main/resources/META-INF/kodama/relationships.json
     */
    private fun generateMetadataJson(relationships: List<RelationshipModel>, packageName: String) {
        try {
            // Generate resource file (not Kotlin source)
            val file = codeGenerator.createNewFile(
                dependencies = Dependencies(true),
                packageName = "",  // Resources don't have package
                fileName = "relationships",
                extensionName = "json"
            )

            OutputStreamWriter(file).use { writer ->
                writer.write(generateMetadataContent(relationships, packageName))
            }

            logger.info("Kodama KSP: Generated relationships.json metadata for Gradle generator")
        } catch (e: Exception) {
            if (e.javaClass.simpleName == "FileAlreadyExistsException") {
                logger.warn("Kodama KSP: relationships.json already exists, skipping metadata generation")
            } else {
                logger.error("Kodama KSP: Failed to generate relationships metadata: ${e.message}")
                throw e
            }
        }
    }

    /**
     * Generate the JSON content for the metadata file.
     *
     * Format:
     * {
     *   "package": "com.obabichev.kodama.tests.schema",
     *   "relationships": [
     *     {"from": "Person", "to": "Order"},
     *     {"from": "Person", "to": "Profile"}
     *   ]
     * }
     */
    private fun generateMetadataContent(relationships: List<RelationshipModel>, packageName: String): String {
        return buildString {
            appendLine("{")
            appendLine("  \"package\": \"$packageName\",")
            appendLine("  \"relationships\": [")

            relationships.forEachIndexed { index, rel ->
                val comma = if (index < relationships.size - 1) "," else ""
                appendLine("    {\"from\": \"${rel.sourceTable}\", \"to\": \"${rel.targetTable}\"}$comma")
            }

            appendLine("  ]")
            append("}")
        }
    }
}
