package com.obabichev.kodama.ksp

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.symbol.*
import com.obabichev.kodama.ksp.model.EntityInterfaceModel
import java.io.OutputStreamWriter

/**
 * Generates entity implementations, factory functions, copy functions, and entity bindings.
 *
 * For each entity interface (e.g., Portfolio), generates:
 * 1. Internal implementation: `internal data class PortfolioImpl(...) : Portfolio`
 * 2. Factory function: `fun Portfolio(...): Portfolio = PortfolioImpl(...)`
 * 3. Copy function: `fun Portfolio.copy(...): Portfolio`
 * 4. Entity binding: `object PortfolioEntityBinding : EntityBinding<Portfolio, ID>`
 * 5. Auto-registration: Registers binding in EntityBindingRegistry
 */
class EntityImplementationGenerator(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger
) {

    fun generateEntityImplementations(entities: List<EntityInterfaceModel>, targetPackage: String) {
        if (entities.isEmpty()) {
            logger.info("Kodama KSP: No entities to generate")
            return
        }

        logger.info("Kodama KSP: Generating implementations for ${entities.size} entity interfaces")

        entities.forEach { entity ->
            try {
                generateForEntity(entity, targetPackage)
                logger.info("Kodama KSP: Generated implementation for ${entity.simpleName}")
            } catch (e: Exception) {
                logger.error("Kodama KSP: Failed to generate entity ${entity.simpleName}: ${e.message}")
            }
        }

        // Generate entity binding registry
        generateBindingRegistry(entities, targetPackage)
    }

    private fun generateForEntity(entity: EntityInterfaceModel, targetPackage: String) {
        val fileName = "${entity.simpleName}Impl"

        try {
            val outputFile = codeGenerator.createNewFile(
                dependencies = Dependencies(false, entity.containingFile),
                packageName = targetPackage,
                fileName = fileName
            )

            OutputStreamWriter(outputFile).use { writer ->
                writer.write(generateEntityCode(entity, targetPackage))
            }
        } catch (e: Exception) {
            // FileAlreadyExistsException means file was created in an earlier processing round
            if (e.javaClass.simpleName != "FileAlreadyExistsException") {
                throw e
            }
            // File already exists from earlier round, this is normal for KSP multi-round processing
        }
    }

    private fun generateEntityCode(entity: EntityInterfaceModel, targetPackage: String): String {
        return buildString {
            // File header
            appendLine("@file:Suppress(\"UNCHECKED_CAST\", \"FunctionName\")")
            appendLine()
            appendLine("package $targetPackage")
            appendLine()

            // Imports
            appendLine("import ${entity.qualifiedName}")
            appendLine("import com.obabichev.kodama.entity.EntityBinding")
            appendLine("import com.obabichev.kodama.entity.EntitySession")
            appendLine("import com.obabichev.kodama.components.Column")
            appendLine("import com.obabichev.kodama.schema.EntityTable")
            appendLine("import java.sql.ResultSet")
            appendLine("import kotlin.reflect.KClass")

            // Import the table object using its qualified name
            appendLine("import ${entity.tableQualifiedName}")

            // Import property types
            entity.propertyImports.forEach { import ->
                appendLine("import $import")
            }

            // Import relationship return types
            entity.relationshipMethods.forEach { method ->
                method.returnTypeImports.forEach { import ->
                    appendLine("import $import")
                }
            }

            // Import target tables used in relationships
            entity.relationshipMethods.forEach { method ->
                method.relationshipData?.let { data ->
                    appendLine("import ${data.targetTableQualifiedName}")
                    if (data is com.obabichev.kodama.ksp.model.ManyToManyData) {
                        appendLine("import ${data.junctionTableQualifiedName}")
                    }
                }
            }

            appendLine()

            // 1. Implementation data class
            appendLine("/**")
            appendLine(" * Internal implementation of ${entity.simpleName}.")
            appendLine(" * Generated by Kodama KSP processor.")
            appendLine(" */")
            append("internal data class ${entity.simpleName}Impl(")
            entity.properties.forEachIndexed { index, prop ->
                appendLine()
                append("    override val ${prop.name}: ${prop.typeName}")
                if (index < entity.properties.lastIndex) append(",")
            }
            appendLine()
            append(") : ${entity.simpleName}")

            // Implement relationship methods if any exist
            if (entity.relationshipMethods.isNotEmpty()) {
                appendLine(" {")
                entity.relationshipMethods.forEach { method ->
                    appendLine()
                    appendLine("    override fun ${method.name}(session: EntitySession): ${method.returnType} {")

                    if (method.relationshipData != null) {
                        generateRelationshipImplementation(method, entity, this)
                    } else {
                        appendLine("        throw NotImplementedError(\"Relationship method ${method.name}() not yet generated. Use manual implementation or wait for future Kodama version.\")")
                    }

                    appendLine("    }")
                }
                append("}")
            }
            appendLine()
            appendLine()

            // 2. Factory function
            appendLine("/**")
            appendLine(" * Factory function to create ${entity.simpleName} instances.")
            appendLine(" * Generated by Kodama KSP processor.")
            appendLine(" */")
            append("fun ${entity.simpleName}(")
            entity.properties.forEachIndexed { index, prop ->
                appendLine()
                append("    ${prop.name}: ${prop.typeName}")
                if (index < entity.properties.lastIndex) append(",")
            }
            appendLine()
            append("): ${entity.simpleName} = ${entity.simpleName}Impl(")
            entity.properties.forEachIndexed { index, prop ->
                append(prop.name)
                if (index < entity.properties.lastIndex) append(", ")
            }
            appendLine(")")
            appendLine()

            // 3. Copy function
            appendLine("/**")
            appendLine(" * Extension function to copy ${entity.simpleName} with optional property changes.")
            appendLine(" * Generated by Kodama KSP processor.")
            appendLine(" */")
            append("fun ${entity.simpleName}.copy(")
            entity.properties.forEachIndexed { index, prop ->
                appendLine()
                append("    ${prop.name}: ${prop.typeName} = this.${prop.name}")
                if (index < entity.properties.lastIndex) append(",")
            }
            appendLine()
            append("): ${entity.simpleName} = ${entity.simpleName}Impl(")
            entity.properties.forEachIndexed { index, prop ->
                append(prop.name)
                if (index < entity.properties.lastIndex) append(", ")
            }
            appendLine(")")
            appendLine()

            // 4. Entity binding
            val idTypeName = entity.idProperty?.typeName ?: "Int"
            appendLine("/**")
            appendLine(" * Entity binding for ${entity.simpleName}.")
            appendLine(" * Maps between ${entity.simpleName} instances and database rows.")
            appendLine(" * Generated by Kodama KSP processor.")
            appendLine(" */")
            appendLine("object ${entity.simpleName}EntityBinding : EntityBinding<${entity.simpleName}, $idTypeName> {")
            appendLine()
            appendLine("    override val entityClass = ${entity.simpleName}::class")
            appendLine()
            appendLine("    override val table: EntityTable<${entity.simpleName}>")
            appendLine("        get() = ${entity.tableObjectName}")
            appendLine()
            appendLine("    override fun entityId(entity: ${entity.simpleName}): $idTypeName {")
            appendLine("        return entity.${entity.idProperty?.name ?: "id"}")
            appendLine("    }")
            appendLine()
            appendLine("    override fun primaryKeyColumns(): List<Column<*>> {")
            appendLine("        return listOf(${entity.tableObjectName}.${entity.idProperty?.tablePropertyName ?: "id"})")
            appendLine("    }")
            appendLine()
            appendLine("    override fun toEntity(resultSet: ResultSet): ${entity.simpleName} {")
            appendLine("        return ${entity.simpleName}(")
            entity.properties.forEachIndexed { index, prop ->
                val getter = getResultSetGetter(prop.typeName, prop.columnName)
                append("            ${prop.name} = $getter")
                if (index < entity.properties.lastIndex) appendLine(",") else appendLine()
            }
            appendLine("        )")
            appendLine("    }")
            appendLine()
            appendLine("    override fun toInsertValues(entity: ${entity.simpleName}): Map<Column<*>, Any?> {")
            appendLine("        return mapOf(")
            entity.properties.filter { !it.isAutoGenerated }.forEachIndexed { index, prop ->
                append("            ${entity.tableObjectName}.${prop.tablePropertyName} to entity.${prop.name}")
                val lastNonAuto = entity.properties.filter { !it.isAutoGenerated }.lastIndex
                if (index < lastNonAuto) appendLine(",") else appendLine()
            }
            appendLine("        )")
            appendLine("    }")
            appendLine()
            appendLine("    override fun toUpdateValues(entity: ${entity.simpleName}, old: ${entity.simpleName}): Map<Column<*>, Any?> {")
            appendLine("        val changes = mutableMapOf<Column<*>, Any?>()")
            entity.properties.filter { !it.isPrimaryKey && !it.isAutoGenerated }.forEach { prop ->
                appendLine("        if (entity.${prop.name} != old.${prop.name}) {")
                appendLine("            changes[${entity.tableObjectName}.${prop.tablePropertyName}] = entity.${prop.name}")
                appendLine("        }")
            }
            appendLine("        return changes")
            appendLine("    }")
            appendLine("}")
        }
    }

    private fun getResultSetGetter(typeName: String, columnName: String): String {
        val isNullable = typeName.endsWith("?")
        val baseType = typeName.removeSuffix("?")

        return when (baseType) {
            "Int", "kotlin.Int" -> if (isNullable) {
                "resultSet.getInt(\"$columnName\").let { if (resultSet.wasNull()) null else it }"
            } else {
                "resultSet.getInt(\"$columnName\")"
            }
            "Long", "kotlin.Long" -> if (isNullable) {
                "resultSet.getLong(\"$columnName\").let { if (resultSet.wasNull()) null else it }"
            } else {
                "resultSet.getLong(\"$columnName\")"
            }
            "Short", "kotlin.Short" -> if (isNullable) {
                "resultSet.getShort(\"$columnName\").let { if (resultSet.wasNull()) null else it }"
            } else {
                "resultSet.getShort(\"$columnName\")"
            }
            "String", "kotlin.String" -> "resultSet.getString(\"$columnName\")"
            "Boolean", "kotlin.Boolean" -> if (isNullable) {
                "resultSet.getBoolean(\"$columnName\").let { if (resultSet.wasNull()) null else it }"
            } else {
                "resultSet.getBoolean(\"$columnName\")"
            }
            "Double", "kotlin.Double" -> if (isNullable) {
                "resultSet.getDouble(\"$columnName\").let { if (resultSet.wasNull()) null else it }"
            } else {
                "resultSet.getDouble(\"$columnName\")"
            }
            "Float", "kotlin.Float" -> if (isNullable) {
                "resultSet.getFloat(\"$columnName\").let { if (resultSet.wasNull()) null else it }"
            } else {
                "resultSet.getFloat(\"$columnName\")"
            }
            "BigDecimal", "java.math.BigDecimal" -> "resultSet.getBigDecimal(\"$columnName\")"
            "LocalDate", "java.time.LocalDate" -> if (isNullable) {
                "resultSet.getDate(\"$columnName\")?.toLocalDate()"
            } else {
                "resultSet.getDate(\"$columnName\").toLocalDate()"
            }
            "LocalTime", "java.time.LocalTime" -> if (isNullable) {
                "resultSet.getTime(\"$columnName\")?.toLocalTime()"
            } else {
                "resultSet.getTime(\"$columnName\").toLocalTime()"
            }
            "LocalDateTime", "java.time.LocalDateTime" -> if (isNullable) {
                "resultSet.getTimestamp(\"$columnName\")?.toLocalDateTime()"
            } else {
                "resultSet.getTimestamp(\"$columnName\").toLocalDateTime()"
            }
            "OffsetDateTime", "java.time.OffsetDateTime" -> "resultSet.getObject(\"$columnName\", OffsetDateTime::class.java)"
            "OffsetTime", "java.time.OffsetTime" -> "resultSet.getObject(\"$columnName\", OffsetTime::class.java)"
            else -> if (isNullable) {
                "resultSet.getObject(\"$columnName\") as? $baseType"
            } else {
                "resultSet.getObject(\"$columnName\") as $baseType"
            }
        }
    }

    /**
     * Generate relationship method implementation based on relationship type.
     */
    private fun generateRelationshipImplementation(
        method: com.obabichev.kodama.ksp.model.RelationshipMethodModel,
        entity: EntityInterfaceModel,
        builder: StringBuilder
    ) {
        val data = method.relationshipData ?: return
        val idProperty = entity.idProperty ?: return

        builder.apply {
            when (data) {
                is com.obabichev.kodama.ksp.model.OneToManyData -> {
                    // Extract target entity type from List<TargetEntity>
                    val targetEntityType = method.returnType.removePrefix("List<").removeSuffix(">")

                    appendLine("        // Check eager loading cache first")
                    appendLine("        val cached = session.getCachedRelationship<$targetEntityType>(")
                    appendLine("            sourceEntityType = ${entity.simpleName}::class,")
                    appendLine("            sourceEntityId = ${idProperty.name},")
                    appendLine("            relationshipName = \"${method.name}\"")
                    appendLine("        )")
                    appendLine("        if (cached != null) return cached")
                    appendLine()
                    appendLine("        // Load related $targetEntityType entities using findByForeignKey")
                    appendLine("        return session.findByForeignKey<$targetEntityType, ${idProperty.typeName}, ${idProperty.typeName}>(")
                    appendLine("            ${data.targetTableName},")
                    appendLine("            ${data.targetTableName}.${data.foreignKeyColumn},")
                    appendLine("            ${idProperty.name}")
                    appendLine("        )")
                }

                is com.obabichev.kodama.ksp.model.ManyToOneData -> {
                    val targetEntityType = method.returnType
                    val foreignKeyProperty = entity.properties.firstOrNull { it.tablePropertyName == data.foreignKeyColumn || it.name == data.foreignKeyColumn }

                    if (foreignKeyProperty != null) {
                        appendLine("        // Check eager loading cache first")
                        appendLine("        val cached = session.getCachedRelationship<$targetEntityType>(")
                        appendLine("            sourceEntityType = ${entity.simpleName}::class,")
                        appendLine("            sourceEntityId = ${idProperty.name},")
                        appendLine("            relationshipName = \"${method.name}\"")
                        appendLine("        )")
                        appendLine("        if (cached != null) return cached.firstOrNull() ?: error(\"${targetEntityType} with id \$${foreignKeyProperty.name} not found\")")
                        appendLine()
                        appendLine("        // Load related $targetEntityType by ${foreignKeyProperty.name} (many-to-one relationship)")
                        appendLine("        return session.find<$targetEntityType>(${foreignKeyProperty.name})")
                        appendLine("            ?: error(\"${targetEntityType} with id \$${foreignKeyProperty.name} not found\")")
                    } else {
                        appendLine("        throw NotImplementedError(\"Could not find foreign key property for ${data.foreignKeyColumn}\")")
                    }
                }

                is com.obabichev.kodama.ksp.model.ManyToManyData -> {
                    val targetEntityType = method.returnType.removePrefix("List<").removeSuffix(">")

                    appendLine("        // Check eager loading cache first")
                    appendLine("        val cached = session.getCachedRelationship<$targetEntityType>(")
                    appendLine("            sourceEntityType = ${entity.simpleName}::class,")
                    appendLine("            sourceEntityId = ${idProperty.name},")
                    appendLine("            relationshipName = \"${method.name}\"")
                    appendLine("        )")
                    appendLine("        if (cached != null) return cached")
                    appendLine()
                    appendLine("        // Load related $targetEntityType entities through ${data.junctionTableName} junction table")
                    appendLine("        return session.findManyToMany<$targetEntityType, ${idProperty.typeName}, ${idProperty.typeName}, ${idProperty.typeName}>(")
                    appendLine("            targetTable = ${data.targetTableName},")
                    appendLine("            junctionTable = ${data.junctionTableName},")
                    appendLine("            sourceForeignKeyColumn = ${data.junctionTableName}.${data.sourceForeignKeyColumn},")
                    appendLine("            targetForeignKeyColumn = ${data.junctionTableName}.${data.targetForeignKeyColumn},")
                    appendLine("            targetPrimaryKeyColumn = ${data.targetTableName}.${data.targetPrimaryKeyColumn},")
                    appendLine("            sourceForeignKeyValue = ${idProperty.name}")
                    appendLine("        )")
                }
            }
        }
    }

    private fun generateBindingRegistry(entities: List<EntityInterfaceModel>, targetPackage: String) {
        val fileName = "KodamaBindingRegistry"

        try {
            val outputFile = codeGenerator.createNewFile(
                dependencies = Dependencies(false),
                packageName = targetPackage,
                fileName = fileName
            )

            OutputStreamWriter(outputFile).use { writer ->
                writer.write(buildString {
                    appendLine("@file:Suppress(\"unused\")")
                    appendLine()
                    appendLine("package $targetPackage")
                    appendLine()
                    appendLine("import com.obabichev.kodama.entity.EntityBinding")
                    appendLine("import com.obabichev.kodama.entity.EntitySession")
                    appendLine()
                    appendLine("/**")
                    appendLine(" * Auto-registration object for entity bindings.")
                    appendLine(" * Automatically sets up EntitySession.autoBindingProvider on initialization.")
                    appendLine(" * Generated by Kodama KSP processor.")
                    appendLine(" */")
                    appendLine("object KodamaBindingRegistry {")
                    appendLine()
                    appendLine("    /**")
                    appendLine("     * All entity bindings in this project.")
                    appendLine("     */")
                    appendLine("    val bindings: List<EntityBinding<*, *>> = listOf(")
                    entities.forEachIndexed { index, entity ->
                        append("        ${entity.simpleName}EntityBinding")
                        if (index < entities.lastIndex) appendLine(",") else appendLine()
                    }
                    appendLine("    )")
                    appendLine()
                    appendLine("    init {")
                    appendLine("        // Build a map for O(1) lookup")
                    appendLine("        val bindingMap = bindings.associateBy { it.entityClass }")
                    appendLine()
                    appendLine("        // Auto-set the provider if not already set")
                    appendLine("        if (EntitySession.autoBindingProvider == null) {")
                    appendLine("            EntitySession.autoBindingProvider = { entityClass ->")
                    appendLine("                bindingMap[entityClass]")
                    appendLine("                    // Handle impl classes (PortfolioImpl -> Portfolio)")
                    appendLine("                    ?: bindingMap.entries.firstOrNull { (key, _) ->")
                    appendLine("                        key.simpleName == entityClass.simpleName?.removeSuffix(\"Impl\")")
                    appendLine("                    }?.value")
                    appendLine("            }")
                    appendLine("        }")
                    appendLine("    }")
                    appendLine("}")
                })
            }

            // Generate resource file for auto-discovery
            // This allows EntitySession to automatically find and initialize the registry
            try {
                val resourceFile = codeGenerator.createNewFile(
                    dependencies = Dependencies(false),
                    packageName = "META-INF.kodama",
                    fileName = "binding-registry",
                    extensionName = "txt"
                )
                resourceFile.writer().use { writer ->
                    writer.write("$targetPackage.KodamaBindingRegistry")
                }
            } catch (e: Exception) {
                // Ignore if file already exists
                if (e.javaClass.simpleName != "FileAlreadyExistsException") {
                    logger.warn("Kodama KSP: Could not create registry resource file: ${e.message}")
                }
            }
        } catch (e: Exception) {
            // FileAlreadyExistsException means file was created in an earlier processing round
            if (e.javaClass.simpleName != "FileAlreadyExistsException") {
                throw e
            }
            // File already exists from earlier round, this is normal for KSP multi-round processing
        }
    }
}
