package com.obabichev.kodama.compiler.transform

import com.obabichev.kodama.compiler.data.*

/**
 * Transforms discovered patterns from raw maps into structured, type-safe data classes.
 *
 * The DataTransformer acts as a bridge between the pattern discovery phase
 * (which uses raw maps and strings) and the generator phase (which uses
 * structured data classes).
 *
 * Responsibilities:
 * - Convert table metadata maps → TableInfo objects
 * - Extract column information → ColumnInfo objects
 * - Build query combinations → QueryCombinationInfo objects
 * - Identify subqueries → SubqueryInfo objects
 * - Extract selection markers → MarkerInfo objects
 *
 * Example usage:
 * ```
 * val discoveredData = patternDiscovery.discover()
 * val transformer = DataTransformer(tableMetadata, discoveredData)
 * val structuredData = transformer.transform()
 *
 * // Use structured data with generators
 * val generators = GeneratorFactory(structuredData).createAllGenerators()
 * ```
 *
 * This separation enables:
 * - Type-safe generator inputs
 * - Easy testing of generators with mock data
 * - Clear boundary between discovery and generation
 * - Potential for multiple transformer implementations
 */
class DataTransformer(
    private val tableMetadata: Map<String, Map<String, Any>>,
    private val discoveredData: Map<String, Any>,
    private val generatedPackage: String
) {

    /**
     * Container for all transformed, structured data.
     */
    data class TransformedData(
        val tables: List<TableInfo>,
        val queryCombinations: List<QueryCombinationInfo>,
        val subqueries: List<SubqueryInfo>,
        val markers: List<MarkerInfo>
    )

    /**
     * Performs the transformation from raw discovered data to structured data.
     */
    fun transform(): TransformedData {
        val tables = transformTables()
        val subqueries = transformSubqueries()

        // Convert subqueries to TableInfo for combination lookup
        val subqueryTables = subqueries.map { subquery ->
            TableInfo(
                name = subquery.name,
                packageName = generatedPackage,  // Subqueries are in generated package
                sqlTableName = subquery.sqlAlias,
                columns = subquery.columns.map { col ->
                    ColumnInfo(
                        propertyName = col.propertyName,
                        sqlColumnName = col.sqlColumnName,
                        kotlinType = col.kotlinType,
                        isNullable = false,
                        isAutoGenerated = false,
                        isPrimaryKey = false
                    )
                },
                isSubquery = true
            )
        }

        // Pass both regular tables and subquery tables for combination lookup
        val allTablesForLookup = tables + subqueryTables
        val queryCombinations = transformQueryCombinations(allTablesForLookup)
        val markers = transformMarkers()

        return TransformedData(
            tables = tables,
            queryCombinations = queryCombinations,
            subqueries = subqueries,
            markers = markers
        )
    }

    /**
     * Transforms table metadata into TableInfo objects.
     */
    private fun transformTables(): List<TableInfo> {
        return tableMetadata.map { (tableName, metadata) ->
            val columns = transformColumns(metadata)
            TableInfo(
                name = tableName,
                packageName = metadata["packageName"] as? String ?: "",  // Extract packageName
                sqlTableName = metadata["sqlTableName"] as? String ?: tableName.lowercase(),
                columns = columns
            )
        }
    }

    /**
     * Transforms column metadata into ColumnInfo objects.
     */
    @Suppress("UNCHECKED_CAST")
    private fun transformColumns(tableMetadata: Map<String, Any>): List<ColumnInfo> {
        val columnsData = tableMetadata["columns"] as? List<Map<String, Any>> ?: emptyList()
        return columnsData.map { columnData ->
            ColumnInfo(
                propertyName = columnData["propertyName"] as String,
                sqlColumnName = columnData["sqlColumnName"] as String,
                kotlinType = columnData["kotlinType"] as String,
                isNullable = columnData["isNullable"] as? Boolean ?: false,
                isAutoGenerated = columnData["isAutoGenerated"] as? Boolean ?: false
            )
        }
    }

    /**
     * Transforms query combination patterns into QueryCombinationInfo objects.
     */
    @Suppress("UNCHECKED_CAST")
    private fun transformQueryCombinations(tables: List<TableInfo>): List<QueryCombinationInfo> {
        val combinationJoinTypesData = discoveredData["combinationJoinTypes"] as? Map<String, List<Map<String, Any?>>> ?: emptyMap()
        val tableMap = tables.associateBy { it.name }

        // Transform each entry in combinationJoinTypesData into a QueryCombinationInfo
        // Key format: "Person_Order:INNER" or just "Person" for single tables
        val queryCombinations = combinationJoinTypesData.mapNotNull { (combinationKey, joinTypesForCombination) ->
            // Extract table names from key (before the colon, if present)
            val tableNames = combinationKey.split(":")[0].split("_")

            if (tableNames.isEmpty()) {
                return@mapNotNull null  // Skip empty combinations
            }

            if (tableNames.size == 1) {
                // Single table query - just a base table, no joins
                val baseTableInfo = tableMap[tableNames[0]] ?: return@mapNotNull null
                QueryCombinationInfo(
                    baseTable = baseTableInfo,
                    joinedTables = emptyList()
                )
            } else {
                // Multi-table query - first table is base, rest are joins
                val baseTableInfo = tableMap[tableNames[0]] ?: return@mapNotNull null
                val joinedTableInfos = tableNames.drop(1).mapIndexedNotNull { index, tableName ->
                    val table = tableMap[tableName] ?: return@mapIndexedNotNull null

                    // Get join type from discovered data (index + 1 because base table is at index 0)
                    val joinTypeStr = joinTypesForCombination.getOrNull(index + 1)?.get("joinType") as? String
                    val joinType = when (joinTypeStr) {
                        "INNER" -> JoinType.INNER
                        "LEFT" -> JoinType.LEFT
                        "RIGHT" -> JoinType.RIGHT
                        "FULL" -> JoinType.FULL
                        else -> JoinType.INNER  // Default to INNER if not specified
                    }

                    JoinedTableInfo(
                        table = table,
                        joinType = joinType
                    )
                }

                QueryCombinationInfo(
                    baseTable = baseTableInfo,
                    joinedTables = joinedTableInfos
                )
            }
        }.toMutableList()

        // Capture regular combinations BEFORE adding any subquery combinations
        val regularCombinations = queryCombinations.toList()

        // Add single-table combinations for all subqueries
        // These are needed for fromAliased(SubqueryMarker) { ... } patterns
        val subqueryTables = tables.filter { it.isSubquery }
        subqueryTables.forEach { subqueryTable ->
            val singleTableCombination = QueryCombinationInfo(
                baseTable = subqueryTable,
                joinedTables = emptyList(),
                isSynthetic = true  // Mark as synthetic
            )
            val exists = queryCombinations.any {
                it.tables.size == 1 && it.tables[0].name == subqueryTable.name
            }
            if (!exists) {
                queryCombinations.add(singleTableCombination)
            }
        }

        // Generate ONLY the single-table + subquery combinations for inline joinAliased support
        // Multi-table + subquery combinations are rarely used and cause code explosion
        // Users can chain multiple joinAliased calls if needed: from(T1).joinAliased(SQ1).joinAliased(SQ2)

        subqueryTables.forEach { subqueryTable ->
            regularCombinations.filter { it.tables.size == 1 }.forEach { baseCombination ->
                // Generate single-table + subquery for ALL join types (INNER, LEFT, RIGHT, FULL)
                // This enables .joinAliased(), .leftJoinAliased(), .rightJoinAliased(), .fullJoinAliased()
                listOf(JoinType.INNER, JoinType.LEFT, JoinType.RIGHT, JoinType.FULL).forEach { joinType ->
                    val combination = QueryCombinationInfo(
                        baseTable = baseCombination.baseTable,
                        joinedTables = listOf(JoinedTableInfo(subqueryTable, joinType)),
                        isSynthetic = true  // Mark as synthetic
                    )
                    val exists = queryCombinations.any {
                        it.tables.map { t -> t.name } == combination.tables.map { t -> t.name } &&
                        it.joinPattern == combination.joinPattern
                    }
                    if (!exists) {
                        queryCombinations.add(combination)
                    }
                }
            }
        }

        return queryCombinations.distinctBy { combination ->
            // Deduplicate by BOTH table names AND join pattern
            // This ensures Person INNER Order and Person LEFT Order are separate combinations
            val tableNames = combination.tables.map { it.name }.joinToString("_")
            val joinPattern = combination.joinPattern
            "$tableNames:$joinPattern"
        }
    }

    /**
     * Transforms subquery patterns into SubqueryInfo objects.
     */
    @Suppress("UNCHECKED_CAST")
    private fun transformSubqueries(): List<SubqueryInfo> {
        val subqueriesData = discoveredData["subqueries"] as? List<Map<String, Any>> ?: emptyList()

        return subqueriesData.map { subqueryData ->
            val name = subqueryData["name"] as String
            val columnsData = subqueryData["columns"] as? List<Map<String, Any>> ?: emptyList()
            val columns = columnsData.map { columnData ->
                SubqueryColumnInfo(
                    propertyName = columnData["propertyName"] as String,
                    sqlColumnName = columnData["sqlColumnName"] as String,
                    kotlinType = columnData["kotlinType"] as String
                )
            }
            val sourceTables = subqueryData["sourceTables"] as? List<String> ?: emptyList()

            SubqueryInfo(
                name = name,
                sqlAlias = subqueryData["sqlAlias"] as? String ?: name.lowercase(),
                columns = columns,
                sourceTables = sourceTables
            )
        }
    }

    /**
     * Transforms selection marker patterns into MarkerInfo objects.
     */
    @Suppress("UNCHECKED_CAST")
    private fun transformMarkers(): List<MarkerInfo> {
        val markersData = discoveredData["markers"] as? List<Map<String, Any>> ?: emptyList()

        return markersData.map { markerData ->
            val interfaceName = markerData["interfaceName"] as String
            val propertyName = interfaceName.replaceFirstChar { it.lowercase() }
            val sqlAliasStyleStr = markerData["sqlAliasStyle"] as? String ?: "SNAKE_CASE"
            val sqlAliasStyle = when (sqlAliasStyleStr) {
                "CAMEL_CASE" -> SqlAliasStyle.CAMEL_CASE
                "SNAKE_CASE" -> SqlAliasStyle.SNAKE_CASE
                else -> SqlAliasStyle.SNAKE_CASE
            }

            MarkerInfo(
                interfaceName = interfaceName,
                propertyName = propertyName,
                packageName = generatedPackage,
                resultType = markerData["resultType"] as? String ?: "Number",
                sqlAliasStyle = sqlAliasStyle
            )
        }
    }

}

