package com.obabichev.kodama.compiler.transform

import com.obabichev.kodama.compiler.data.*

/**
 * Transforms discovered patterns from raw maps into structured, type-safe data classes.
 *
 * The DataTransformer acts as a bridge between the pattern discovery phase
 * (which uses raw maps and strings) and the generator phase (which uses
 * structured data classes).
 *
 * Responsibilities:
 * - Convert table metadata maps → TableInfo objects
 * - Extract column information → ColumnInfo objects
 * - Build query combinations → QueryCombinationInfo objects
 * - Identify subqueries → SubqueryInfo objects
 * - Extract selection markers → MarkerInfo objects
 *
 * Example usage:
 * ```
 * val discoveredData = patternDiscovery.discover()
 * val transformer = DataTransformer(tableMetadata, discoveredData)
 * val structuredData = transformer.transform()
 *
 * // Use structured data with generators
 * val generators = GeneratorFactory(structuredData).createAllGenerators()
 * ```
 *
 * This separation enables:
 * - Type-safe generator inputs
 * - Easy testing of generators with mock data
 * - Clear boundary between discovery and generation
 * - Potential for multiple transformer implementations
 */
class DataTransformer(
    private val tableMetadata: Map<String, Map<String, Any>>,
    private val discoveredData: Map<String, Any>,
    private val generatedPackage: String
) {

    /**
     * Container for all transformed, structured data.
     */
    data class TransformedData(
        val tables: List<TableInfo>,
        val queryCombinations: List<QueryCombinationInfo>,
        val subqueries: List<SubqueryInfo>,
        val markers: List<MarkerInfo>,
        val markerCombinations: List<MarkerCombinationInfo>
    )

    /**
     * Performs the transformation from raw discovered data to structured data.
     */
    fun transform(): TransformedData {
        val tables = transformTables()
        val subqueries = transformSubqueries()

        // Convert subqueries to TableInfo for combination lookup
        val subqueryTables = subqueries.map { subquery ->
            TableInfo(
                name = subquery.name,
                sqlTableName = subquery.sqlAlias,
                columns = subquery.columns.map { col ->
                    ColumnInfo(
                        propertyName = col.propertyName,
                        sqlColumnName = col.sqlColumnName,
                        kotlinType = col.kotlinType,
                        isNullable = false,
                        isAutoGenerated = false,
                        isPrimaryKey = false
                    )
                },
                isSubquery = true
            )
        }

        // Pass both regular tables and subquery tables for combination lookup
        val allTablesForLookup = tables + subqueryTables
        val queryCombinations = transformQueryCombinations(allTablesForLookup)
        val markers = transformMarkers()
        val markerCombinations = transformMarkerCombinations(markers)

        return TransformedData(
            tables = tables,
            queryCombinations = queryCombinations,
            subqueries = subqueries,
            markers = markers,
            markerCombinations = markerCombinations
        )
    }

    /**
     * Transforms table metadata into TableInfo objects.
     */
    private fun transformTables(): List<TableInfo> {
        return tableMetadata.map { (tableName, metadata) ->
            val columns = transformColumns(metadata)
            TableInfo(
                name = tableName,
                sqlTableName = metadata["sqlTableName"] as? String ?: tableName.lowercase(),
                columns = columns
            )
        }
    }

    /**
     * Transforms column metadata into ColumnInfo objects.
     */
    @Suppress("UNCHECKED_CAST")
    private fun transformColumns(tableMetadata: Map<String, Any>): List<ColumnInfo> {
        val columnsData = tableMetadata["columns"] as? List<Map<String, Any>> ?: emptyList()
        return columnsData.map { columnData ->
            ColumnInfo(
                propertyName = columnData["propertyName"] as String,
                sqlColumnName = columnData["sqlColumnName"] as String,
                kotlinType = columnData["kotlinType"] as String,
                isNullable = columnData["isNullable"] as? Boolean ?: false,
                isAutoGenerated = columnData["isAutoGenerated"] as? Boolean ?: false
            )
        }
    }

    /**
     * Transforms query combination patterns into QueryCombinationInfo objects.
     */
    @Suppress("UNCHECKED_CAST")
    private fun transformQueryCombinations(tables: List<TableInfo>): List<QueryCombinationInfo> {
        val combinations = discoveredData["queryCombinations"] as? List<List<String>> ?: emptyList()
        val tableMap = tables.associateBy { it.name }

        val queryCombinations = combinations.map { tableNames ->
            val combinationTables = tableNames.mapNotNull { tableMap[it] }
            QueryCombinationInfo(
                tables = combinationTables
            )
        }.toMutableList()

        // Add single-table combinations for all subqueries
        // These are needed for fromAliased(SubqueryMarker) { ... } patterns
        val subqueryTables = tables.filter { it.isSubquery }
        subqueryTables.forEach { subqueryTable ->
            val singleTableCombination = QueryCombinationInfo(tables = listOf(subqueryTable))
            val exists = queryCombinations.any {
                it.tables.size == 1 && it.tables[0].name == subqueryTable.name
            }
            if (!exists) {
                queryCombinations.add(singleTableCombination)
            }
        }

        // Note: Table+Subquery combinations are now only generated if explicitly discovered
        // in the code via .joinAliased(Subquery) or .leftJoinAliased(Subquery) patterns.
        // We no longer auto-generate all possible Table×Subquery combinations (Cartesian product)
        // to avoid bloating the generated code with unused combinations.
        //
        // Previously, this code would generate 15 tables × 6 subqueries = 90 unused combinations.
        // Now we only generate what's actually used in the codebase.

        return queryCombinations.distinctBy { combination ->
            // Deduplicate by table names in the combination
            combination.tables.map { it.name }.joinToString("_")
        }
    }

    /**
     * Transforms subquery patterns into SubqueryInfo objects.
     */
    @Suppress("UNCHECKED_CAST")
    private fun transformSubqueries(): List<SubqueryInfo> {
        val subqueriesData = discoveredData["subqueries"] as? List<Map<String, Any>> ?: emptyList()

        return subqueriesData.map { subqueryData ->
            val name = subqueryData["name"] as String
            val columnsData = subqueryData["columns"] as? List<Map<String, Any>> ?: emptyList()
            val columns = columnsData.map { columnData ->
                SubqueryColumnInfo(
                    propertyName = columnData["propertyName"] as String,
                    sqlColumnName = columnData["sqlColumnName"] as String,
                    kotlinType = columnData["kotlinType"] as String
                )
            }
            val sourceTables = subqueryData["sourceTables"] as? List<String> ?: emptyList()

            SubqueryInfo(
                name = name,
                sqlAlias = subqueryData["sqlAlias"] as? String ?: name.lowercase(),
                columns = columns,
                sourceTables = sourceTables
            )
        }
    }

    /**
     * Transforms selection marker patterns into MarkerInfo objects.
     */
    @Suppress("UNCHECKED_CAST")
    private fun transformMarkers(): List<MarkerInfo> {
        val markersData = discoveredData["markers"] as? List<Map<String, Any>> ?: emptyList()

        return markersData.map { markerData ->
            val interfaceName = markerData["interfaceName"] as String
            val propertyName = interfaceName.replaceFirstChar { it.lowercase() }
            val sqlAliasStyleStr = markerData["sqlAliasStyle"] as? String ?: "SNAKE_CASE"
            val sqlAliasStyle = when (sqlAliasStyleStr) {
                "CAMEL_CASE" -> SqlAliasStyle.CAMEL_CASE
                "SNAKE_CASE" -> SqlAliasStyle.SNAKE_CASE
                else -> SqlAliasStyle.SNAKE_CASE
            }

            MarkerInfo(
                interfaceName = interfaceName,
                propertyName = propertyName,
                packageName = generatedPackage,
                resultType = markerData["resultType"] as? String ?: "Number",
                sqlAliasStyle = sqlAliasStyle
            )
        }
    }

    /**
     * Transforms marker combination patterns into MarkerCombinationInfo objects.
     */
    @Suppress("UNCHECKED_CAST")
    private fun transformMarkerCombinations(allMarkers: List<MarkerInfo>): List<MarkerCombinationInfo> {
        val combinationsData = discoveredData["markerCombinations"] as? List<List<String>> ?: emptyList()
        val markerMap = allMarkers.associateBy { it.interfaceName }

        return combinationsData
            .map { markerNames ->
                val markers = markerNames.mapNotNull { markerMap[it] }
                if (markers.isNotEmpty()) {
                    MarkerCombinationInfo(markers)
                } else {
                    null
                }
            }
            .filterNotNull()
            .distinctBy { it.combinationKey }  // Deduplicate by sorted marker names
    }
}

