package com.obabichev.kodama.query

import com.obabichev.kodama.util.toSnakeCase
import kotlin.reflect.KClass

/**
 * Extension function to alias a Query as a SubqueryTable with a type-safe marker.
 *
 * Usage:
 * ```kotlin
 * val subquery = from(Order)
 *     .select { order.userName }
 *     .selectAliased(TotalCost) { sum(order.cost) }
 *     .build()
 *     .aliasAs<UserTotals>()
 * ```
 *
 * The code generator will scan for this pattern and generate a typed SubqueryTable_UserTotals
 * class with the appropriate column accessors.
 *
 * @param T The marker interface type for this subquery (e.g., UserTotals)
 * @return A SubqueryTable that can be used in FROM or JOIN clauses
 */
/**
 * Extension function to alias a Query as a SubqueryTable with a type-safe marker.
 *
 * This function uses the SubqueryRegistry (generated by the compiler plugin) to create
 * the appropriately typed SubqueryTable_X instance. If no specific subquery class exists
 * for the marker, it falls back to creating a generic SubqueryTable.
 *
 * @param T The marker interface type for this subquery (e.g., UserTotals)
 * @return A SubqueryTable instance that implements the marker interface T
 */
inline fun <reified T : Any> Query.aliasAs(): T {
    val markerClass = T::class

    // Try to find the SubqueryRegistry class in the same package as the marker interface
    return try {
        // Get the package of the marker interface
        val markerPackage = markerClass.java.packageName

        // Try to load SubqueryRegistry from the marker's package
        val registryClass = Class.forName("$markerPackage.SubqueryRegistry")
        val createMethod = registryClass.getDeclaredMethod("createSubquery", KClass::class.java, Query::class.java)
        val registry = registryClass.kotlin.objectInstance
        createMethod.invoke(registry, markerClass, this) as T
    } catch (e: Exception) {
        // Fallback if registry not found or invocation failed
        // This should not happen in normal usage with properly generated code
        val aliasName = markerClass.simpleName
            ?.replaceFirstChar { it.lowercase() }
            ?.toSnakeCase()
            ?: error("Cannot derive alias name from marker class")

        error("SubqueryRegistry not found for marker ${markerClass.simpleName}. " +
              "Make sure code generation has run. Original error: ${e.message}")
    }
}

/**
 * Generic subquery builder function.
 *
 * Usage:
 * ```kotlin
 * .from(subquery {
 *     from(Order)
 *         .select { order.userName }
 *         .build()
 *         .aliasAs<UserOrders>()
 * })
 * ```
 *
 * @param builder Lambda that returns a SubqueryTable
 * @return The SubqueryTable created by the builder
 */
inline fun <T : SubqueryTable> subquery(builder: () -> T): T {
    return builder()
}
