package com.obabichev.kodama.compiler

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.tasks.*
import java.io.File

/**
 * New table-based code generator.
 * Instead of scanning data classes, this reads from registered Table objects.
 *
 * The generation happens at runtime when tables are first accessed,
 * so we need to scan test files to discover which table combinations are used.
 */
@CacheableTask
abstract class KodamaTableBasedCodegenTask : DefaultTask() {

    @get:InputDirectory
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val testDir: DirectoryProperty

    @get:InputDirectory
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val schemaDir: DirectoryProperty

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    init {
        testDir.convention(project.layout.projectDirectory.dir("src/test/kotlin"))
        schemaDir.convention(project.layout.projectDirectory.dir("src/main/kotlin"))
        outputDir.convention(project.layout.buildDirectory.dir("generated/kodama"))
    }

    @TaskAction
    fun generate() {
        val queryOutputFile = outputDir.get().asFile.resolve("com/obabichev/kodama/tests/data/QueryExtensions.kt")

        // Discover tables by scanning schema files
        val tables = mutableSetOf<String>()
        val tableToProperties = mutableMapOf<String, List<String>>()

        // Scan for table definitions: object Xxx : Table(...)
        val schemaFiles = schemaDir.get().asFile.walkTopDown().filter { it.extension == "kt" }
        schemaFiles.forEach { file ->
            val content = file.readText()

            // Match: object TableName : Table("...") { ... }
            val tablePattern = """object\s+(\w+)\s*:\s*Table\s*\([^)]*\)\s*\{([^}]*)\}""".toRegex()
            tablePattern.findAll(content).forEach { match ->
                val tableName = match.groupValues[1].lowercase()
                val tableBody = match.groupValues[2]
                tables.add(tableName)

                // Extract properties from table body only: val xxx = ...
                val propertyPattern = """val\s+(\w+)\s*=""".toRegex()
                val properties = propertyPattern.findAll(tableBody)
                    .map { it.groupValues[1] }
                    .toList()

                if (properties.isNotEmpty()) {
                    tableToProperties[tableName] = properties
                }
            }
        }

        // Discover query combinations from test files
        val queryCombinations = mutableSetOf<List<String>>()

        val testFiles = testDir.get().asFile.walkTopDown().filter { it.extension == "kt" }
        testFiles.forEach { file ->
            val content = file.readText()

            // Match query chains: query().from(Table).join(Table)...
            // Look for query().from(...) and then capture everything until .select or .where or end
            val queryChainPattern = """query\s*\(\s*\)\s*\.from\s*\([^)]+\)(?:\s*\.join\s*\([^)]+\)(?:\s*\{[^}]*\})?)*""".toRegex()

            queryChainPattern.findAll(content).forEach { chainMatch ->
                val chain = chainMatch.value
                val typesInChain = mutableListOf<String>()

                // Extract table names from the chain
                val tableRefPattern = """(?:from|join)\s*\(\s*(\w+)""".toRegex()
                tableRefPattern.findAll(chain).forEach { typeMatch ->
                    val tableName = typeMatch.groupValues[1].lowercase()
                    typesInChain.add(tableName)
                }

                // Store all prefixes
                if (typesInChain.isNotEmpty()) {
                    for (i in 1..typesInChain.size) {
                        val subCombination = typesInChain.take(i)
                        queryCombinations.add(subCombination)
                    }
                }
            }
        }

        // Generate query extensions
        queryOutputFile.parentFile.mkdirs()
        queryOutputFile.writeText(buildString {
            appendLine("@file:Suppress(\"UNCHECKED_CAST\")")
            appendLine()
            appendLine("package com.obabichev.kodama.tests.data")
            appendLine()
            appendLine("import com.obabichev.kodama.components.JoinType")
            appendLine("import com.obabichev.kodama.query.*")
            appendLine("import com.obabichev.kodama.tests.schema.*")
            appendLine("import com.obabichev.kodama.schema.Table")
            appendLine()
            appendLine("// AUTO-GENERATED by Kodama Compiler Plugin")
            appendLine("// DO NOT EDIT MANUALLY")
            appendLine()

            // Generate accessor classes for each table
            tables.forEach { tableName ->
                val capitalizedName = tableName.replaceFirstChar { it.uppercase() }
                val properties = tableToProperties[tableName] ?: emptyList()

                appendLine("/**")
                appendLine(" * Type-safe accessor for $capitalizedName table")
                appendLine(" */")
                appendLine("class ${capitalizedName}Accessor(")
                appendLine("    private val tableAccessor: TableAccessor")
                appendLine(") {")
                appendLine("    fun all() = tableAccessor.all()")
                appendLine()

                // Add property accessors that directly return columns from the table object
                properties.forEach { propName ->
                    appendLine("    val $propName")
                    appendLine("        get() = $capitalizedName.$propName")
                    appendLine()
                }

                appendLine("}")
                appendLine()
            }

            // Track generated ResultAccessor classes
            val generatedResultAccessors = mutableSetOf<String>()

            // Generate typed builders for each query combination
            queryCombinations.forEach { combination ->
                val typeNames = combination.map { it.replaceFirstChar { c -> c.uppercase() } }
                val builderClassName = "AfterFromQueryBuilder_" + typeNames.joinToString("_")
                val contextClassName = "SelectContext_" + typeNames.joinToString("_")

                appendLine("// ========== ${typeNames.joinToString(" + ")} ==========")
                appendLine()

                // Generate builder class
                appendLine("class $builderClassName(")
                appendLine("    override val state: QueryState")
                appendLine(") : AfterFromQueryBuilderBase")
                appendLine()

                // Generate from() extension only for single-table combinations
                if (combination.size == 1) {
                    val tableName = combination[0]
                    val capitalizedName = tableName.replaceFirstChar { it.uppercase() }

                    appendLine("fun InitialQueryBuilder.from(table: $capitalizedName): $builderClassName {")
                    appendLine("    state._from = state.relations.relation(table)")
                    appendLine("    return $builderClassName(state)")
                    appendLine("}")
                    appendLine()
                }

                // Generate join() extensions
                tables.forEach { newTable ->
                    if (!combination.contains(newTable)) {
                        val newCombination = combination + newTable

                        if (queryCombinations.contains(newCombination)) {
                            val newTableCapitalized = newTable.replaceFirstChar { it.uppercase() }
                            val newBuilderClassName = "AfterFromQueryBuilder_" + newCombination.map { it.replaceFirstChar { c -> c.uppercase() } }.joinToString("_")
                            val jvmName = "join" + typeNames.joinToString("") + newTableCapitalized
                            val joinContextClassName = "JoinContext_" + typeNames.joinToString("_") + "_" + newTableCapitalized

                            // Generate JoinContext
                            appendLine("class $joinContextClassName(")
                            appendLine("    private val state: QueryState,")
                            appendLine("    private val joiningTable: Table")
                            appendLine(") {")

                            combination.forEach { existingTable ->
                                val existingCapitalized = existingTable.replaceFirstChar { it.uppercase() }
                                appendLine("    val $existingTable = ${existingCapitalized}Accessor(TableAccessor($existingCapitalized, state.relations))")
                            }
                            appendLine("    val $newTable = ${newTableCapitalized}Accessor(TableAccessor($newTableCapitalized, state.relations))")

                            appendLine("}")
                            appendLine()

                            // Generate join method
                            appendLine("@JvmName(\"$jvmName\")")
                            appendLine("fun $builderClassName.join(")
                            appendLine("    table: $newTableCapitalized,")
                            appendLine("    type: JoinType = JoinType.INNER,")
                            appendLine("    condition: $joinContextClassName.() -> Pair<com.obabichev.kodama.components.Column<*>, com.obabichev.kodama.components.Column<*>>")
                            appendLine("): $newBuilderClassName {")
                            appendLine("    val relation = state.relations.relation(table)")
                            appendLine("    val context = $joinContextClassName(state, table)")
                            appendLine("    val (leftColumn, rightColumn) = context.condition()")
                            appendLine("    state._joins.add(com.obabichev.kodama.components.Join(type, relation, leftColumn to rightColumn))")
                            appendLine("    return $newBuilderClassName(state)")
                            appendLine("}")
                            appendLine()
                        }
                    }
                }

                // Generate SelectContext
                appendLine("class $contextClassName(")
                appendLine("    private val state: QueryState")
                appendLine(") : SelectContext() {")

                combination.forEach { tableName ->
                    val capitalizedName = tableName.replaceFirstChar { it.uppercase() }
                    appendLine("    val $tableName = ${capitalizedName}Accessor(TableAccessor($capitalizedName, state.relations))")
                }

                appendLine("}")
                appendLine()

                // Generate select() extension
                appendLine("fun $builderClassName.select(block: $contextClassName.() -> Unit): $builderClassName {")
                appendLine("    val context = $contextClassName(state)")
                appendLine("    context.block()")
                appendLine("    state._select = context.selectedColumns")
                appendLine("    return this")
                appendLine("}")
                appendLine()

                // Generate WhereContext
                val whereContextClassName = "WhereContext_" + typeNames.joinToString("_")
                appendLine("class $whereContextClassName(")
                appendLine("    private val state: QueryState")
                appendLine(") {")

                combination.forEach { tableName ->
                    val capitalizedName = tableName.replaceFirstChar { it.uppercase() }
                    appendLine("    val $tableName = ${capitalizedName}Accessor(TableAccessor($capitalizedName, state.relations))")
                }

                appendLine("}")
                appendLine()

                // Generate where() extension
                appendLine("fun $builderClassName.where(block: $whereContextClassName.() -> com.obabichev.kodama.components.expression.Expression): $builderClassName {")
                appendLine("    val context = $whereContextClassName(state)")
                appendLine("    state.whereExpression = context.block()")
                appendLine("    return this")
                appendLine("}")
                appendLine()

                // Generate QueryResult class
                val resultClassName = "QueryResult_" + typeNames.joinToString("_")
                appendLine("class $resultClassName(")
                appendLine("    override val resultSet: java.sql.ResultSet,")
                appendLine("    override val relations: com.obabichev.kodama.query.RelationsContainer,")
                appendLine("    private val selectedColumns: List<com.obabichev.kodama.components.Column<*>>")
                appendLine(") : com.obabichev.kodama.query.QueryResult {")

                combination.forEach { tableName ->
                    val capitalizedName = tableName.replaceFirstChar { it.uppercase() }
                    val resultAccessorClassName = "${capitalizedName}ResultAccessor"
                    appendLine("    val $tableName = $resultAccessorClassName(resultSet, relations, selectedColumns)")
                }

                appendLine("}")
                appendLine()

                // Generate result accessor classes
                combination.forEach { tableName ->
                    val capitalizedName = tableName.replaceFirstChar { it.uppercase() }
                    val resultAccessorClassName = "${capitalizedName}ResultAccessor"

                    if (!generatedResultAccessors.contains(resultAccessorClassName)) {
                        generatedResultAccessors.add(resultAccessorClassName)

                        val properties = tableToProperties[tableName] ?: emptyList()

                        appendLine("class $resultAccessorClassName(")
                        appendLine("    resultSet: java.sql.ResultSet,")
                        appendLine("    relations: com.obabichev.kodama.query.RelationsContainer,")
                        appendLine("    selectedColumns: List<com.obabichev.kodama.components.Column<*>>")
                        appendLine(") : com.obabichev.kodama.query.TableResultAccessor(resultSet, relations, selectedColumns) {")

                        properties.forEach { propName ->
                            appendLine("    val $propName: Any?")
                            appendLine("        get() = readColumn($capitalizedName.$propName)")
                            appendLine()
                        }

                        appendLine("}")
                        appendLine()
                    }
                }

                // Generate execute extension
                appendLine("fun $builderClassName.execute(transaction: com.obabichev.kodama.execute.JdbcTransaction): com.obabichev.kodama.query.QueryResultIterable<$resultClassName> {")
                appendLine("    val query = this.build()")
                appendLine("    val resultSet = transaction.execute(query)")
                appendLine("    return com.obabichev.kodama.query.QueryResultIterable(resultSet, state.relations) { rs, relations ->")
                appendLine("        $resultClassName(rs, relations, query.select)")
                appendLine("    }")
                appendLine("}")
                appendLine()
            }
        })

        logger.lifecycle("Kodama: Generated ${tables.size} tables, ${queryCombinations.size} query combinations")
    }
}
