package com.obabichev.kodama.schema

/**
 * Defines how a column's value is generated during INSERT operations.
 *
 * This determines whether a column must be included as a parameter in generated insert() methods:
 * - AlwaysGenerated: Column is excluded from INSERT (database generates the value)
 * - ClientProvided: Column is required as a parameter in INSERT (client must provide the value)
 *
 * Future phases will add more strategies for DEFAULT values and computed columns.
 */
sealed interface GenerationStrategy {
    /**
     * Value is ALWAYS generated by the database and should NEVER be provided by the client.
     *
     * Examples:
     * - SERIAL, BIGSERIAL, SMALLSERIAL columns (PostgreSQL auto-increment)
     * - INTEGER GENERATED ALWAYS AS IDENTITY (SQL standard auto-increment)
     * - Trigger-generated values
     *
     * INSERT behavior: Column is excluded from INSERT statement and insert() method parameters
     */
    object AlwaysGenerated : GenerationStrategy

    /**
     * Value MUST be provided by the client.
     *
     * This is the default strategy for regular columns.
     *
     * INSERT behavior: Column is required as a parameter in insert() method
     */
    object ClientProvided : GenerationStrategy
}
